# control articles rendered: 
# https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2
project:
  type: website
  render:
    - "*.qmd"
  
execute:
  freeze: auto

website:
  title: "Forwards"
  site-url: https://forwards.github.io/
  description: "R Foundation taskforce on women and other under-represented groups."
  favicon: /images/favicon.ico
  twitter-card:
    site: "@R_Forwards"
  open-graph: true
  
  page-navigation: true
  reader-mode: true
  page-footer: |
      © 2023 Forwards, under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) license.<br>
      
  navbar:
    logo:  /images/forwards.svg
    logo-href: /index.html
    left: 
      # - menu: 
      - text: "About"
        file: about.qmd
      - text: "Community"
        file: community.qmd
      - text: "Conferences"
        file: conferences.qmd
      - text: "Education"
        file: edu/index.qmd
      - text: "Contribution"
        file: contribution.qmd
      - text: "Data"
        file: data.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Other"
        menu:
          - docs/index.qmd
          - privacy-policy.qmd
          - logo-information.qmd

    right: 
      - icon: mastodon
        aria-label: mastodon
        href: https://hachyderm.io/@R_Forwards
        rel: me
      - icon: rss
        href: blog/index.xml
      - icon: envelope
        aria-label: email
        href: mailto:rowforwards@mail.com
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/forwards/website_source
          - text: Report a Bug
            url: https://github.com/forwards/website_source
   
    search: true

format:
  html:
    theme:  
      light: cosmo
      dark: [darkly, theme-dark.scss] #cosmo
    css: styles.css
    toc: true  
    email-obfuscation: references
    include-in-header: analytics.html