# control articles rendered: 
# https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2
project:
  type: website
  resources: 
    - "favicon*"
  render:
    - "*.qmd"
  
execute:
  freeze: auto

website:
  title: "Forwards"
  site-url: https://forwards.github.io/
  favicon: "favicon-32x32.png"
  twitter-card:
    site: "@R_Forwards"
    image: /images/forwards_social.png
  open-graph:
    image: /images/forwards_social.png
  
  page-navigation: true
  reader-mode: true
  page-footer: |
      © 2024 Forwards, under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) license.<br>
      
  navbar:
    logo:  /images/forwards_hex_solid_border.png
    logo-href: /index.html
    left: 
      # - menu: 
      - text: "About"
        file: about.qmd
      - text: "Community"
        file: community.qmd
      - text: "Conferences"
        file: conferences.qmd
      - text: "Education"
        file: edu/index.qmd
      - text: "Contribution"
        file: contribution.qmd
      - text: "Data"
        file: data.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Other"
        menu:
          - docs/index.qmd
          - privacy-policy.qmd
          - logo-information.qmd

    right: 
      - icon: mastodon
        aria-label: mastodon
        href: https://hachyderm.io/@R_Forwards
        rel: me
      - text: "{{< iconify simple-icons:bluesky >}}"
        aria-label: bluesky
        href: https://bsky.app/profile/R-Forwards.hachyderm.io.ap.brid.gy
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/company/103514384
      - icon: rss
        href: blog/index.xml
      - icon: envelope
        aria-label: email
        href: mailto:rowforwards@mail.com
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/forwards/forwards.github.io
          - text: Report a Bug
            url: https://github.com/forwards/forwards.github.io/issues
   
    search: true

format:
  html:
    theme:  
      light: forwards-light.scss
      dark: forwards-dark.scss
    highlight-style: forwards.theme
    css: styles.css
    toc: true  
    email-obfuscation: references
    include-in-header: analytics.html
    description: "R Foundation taskforce on women and other under-represented groups."
