---
title: "About"
---

## Background

The task force was set up by the [R Foundation](https://www.r-project.org/foundation/) in December 2015 to address the underrepresentation of women and rebranded in Janurary 2017 to accommadate more under-represented groups such as LGBT, minority ethnic groups in the R community.

The members of the task force were invited to participate based on their interest in routing for specific under-represented groups and their contributions in the area, to reflect different genders, ethnic groups, work contexts, career stages and aspects of the R project (e.g. CRAN and Bioconductor). Currently, the task force is expanding and welcomes anybody with such interest to join our sub-team. If interested, please contact rowforwards@gmail.com. 

The task force is happy to engage with other individuals and organisations (such as [R-ladies](http://r-ladies.org)) that are concerned about this issue and actively seek outside contributions on specific tasks. 

## Core Team Members

[Heather Turner](linkedin Page)-**Forwards Chair**. Your identitfy outside of Forwards and your association of R communicty(you deem the most important one). A link you think can display more about you (either be work or personal life). **See the below example for Jenny"

[Jenny Bryan](LinkedIn page)- **Forwards team leader for 'On-ramps to becoming a developR"**. She's also an Assoc.Professor of Statistics at the University of British Columbia (on leave) and a [RStudio](https://www.rstudio.com) developer.[More about Jenny ](https://www.stat.ubc.ca/~jenny/)

**All the other 13 core members will follow the above examples**. 




