---
title: "About"
description: Background and structure of the R Foundation taskforce on women and other under-represented groups
---

## Background

The task force was set up by the [R Foundation](https://www.r-project.org/foundation/) in December 2015 to address the underrepresentation of women and rebranded in January 2017 to accommodate more under-represented groups such as LGBT, minority ethnic groups, and people with disabilities in the R community.

The members of the task force were invited to participate based on their interest in routing for specific under-represented groups and their contributions in the area of diversity and inclusion, to reflect different genders, ethnic groups, work contexts, career stages and aspects of the R project (e.g. CRAN and Bioconductor). The task force focuses on particular tasks as outlined below:

- **Accessibility**: Working to improve access to R materials for people with low vision, blindness, hard of hearing, deaf, and other disabilities.

- **Community**: General outreach to help people from under-represented groups get into R and develop as useRs.

- **Conferences**: Focusing on R Foundation conferences, liaising with organizers/program committee on policies and inclusion initiatives.

- **On-ramps**: Creating paths for useRs to develop their skills and make contributions to the R/BioConductor package ecosystem.

- **Social Media**: Posting to Mastodon (bridged to Bluesky) and LinkedIn, soliciting blog posts and publishing them, maintaining website.

- **Surveys**: Running and analysing community surveys, packaging up data and tools and maintaining the [Data](https://forwards.github.io/data/) page.

- **Teaching**: Methodology, materials and workshops designed for under-represented groups.


The activities of the taskforce are recorded in the [minutes of our team meetings](https://github.com/forwards/meetings-public). We are open to new members - if interested, please contact rowforwards@gmail.com.

Forwards is happy to engage with other individuals and organisations (such as [R-Ladies](http://r-ladies.org/)) that are concerned about diversity and inclusion and actively seek outside collaboration on specific tasks.


## Team Members

[Lois Adler-Johnson](https://loisaj.com/) - ([LinkedIn](https://www.linkedin.com/in/loisaj/)/[Bluesky](https://bsky.app/profile/lois-aj.bsky.social)/[GitHub](https://github.com/joislohnson))

[Mine Çetinkaya-Rundel](http://mine-cr.com/) - ([LinkedIn](https://www.linkedin.com/in/minec/)/[Bluesky](https://bsky.app/profile/minecr.bsky.social)/[Mastodon](https://fosstodon.org/@minecr)/[GitHub](https://github.com/mine-cetinkaya-rundel))

Michael Chirico -  ([Bluesky](https://bsky.app/profile/michaelchirico.bsky.social)/[Mastodon](https://fosstodon.org/michaelchirico)/[GitHub](https://github.com/MichaelChirico))

Daniela Cialfi - ([LinkedIn](https://www.linkedin.com/in/daniela-cialfi/?originalSubdomain=it))

[Di Cook](http://dicook.org) - ([LinkedIn](https://au.linkedin.com/in/dianne-cook-a4877a104)/[Bluesky](https://bsky.app/profile/visnut.bsky.social)/[Mastodon](https://aus.social/@visnut)/[GitHub](https://github.com/dicook))

[Paola Corrales](https://paocorrales.github.io/) - ([Mastodon](https://fosstodon.org/deck/@paocorrales)/[GitHub](https://github.com/paocorrales))

Zane Dax - ([GitHub](https://github.com/PythonCoderUnicorn))

[Jesica Formoso](https://jformoso.github.io/) - ([LinkedIn](https://www.linkedin.com/in/jesica-formoso-16ab4649/)/[Bluesky](https://bsky.app/profile/jformoso.bsky.social)/[GitHub](https://github.com/JFormoso))

[gwynn gebeyehu](http://www.nzgwynn.com/) - ([Mastodon](https://mstdn.social/@nzgwynn)/[GitHub](https://github.com/nzgwynn))

[Jonathan Godfrey](https://r-resources.massey.ac.nz/BrailleR) - ([GitHub](https://github.com/ajrgodfrey))

[Julie Josse](http://juliejosse.com/) -  ([LinkedIn](https://www.linkedin.com/in/julie-josse-4886a2140/)/[GitHub](https://github.com/julierennes))

Saranjeet Kaur Bhogal -  ([LinkedIn](https://www.linkedin.com/in/saranjeet-kaur-48ab769b/)/[Bluesky](https://bsky.app/profile/saranjeet.fosstodon.org.ap.brid.gy)/[Mastodon](https://fosstodon.org/@saranjeet)/[GitHub](https://github.com/SaranjeetKaur))

[Ella Kaye](https://ellakaye.co.uk) - ([LinkedIn](https://www.linkedin.com/in/ella-kaye-9b878248/)/[Bluesky](https://bsky.app/profile/ellakaye.co.uk)/[Mastodon](https://fosstodon.org/@ellakaye)/[GitHub](https://github.com/EllaKaye))

Michael Lawrence - ([LinkedIn](https://www.linkedin.com/in/michael-lawrence-74a9b482/)/[GitHub](https://github.com/lawremi))

[Mohammed A Mohammed](https://www.strategyunitwm.nhs.uk/author/mohammed-amin-mohammed)

Kevin O’Brien - ([LinkedIn](https://ie.linkedin.com/in/kobriendublin)/[Bluesky](https://bsky.app/profile/kobriendublin.bsky.social)/[Mastodon](https://fosstodon.org/@kobriendublin)/[GitHub](https://github.com/DragonflyStats))

Imani Oluwafumilayo Maliti - ([LinkedIn](https://www.linkedin.com/in/imanimaliti)/[GitHub](https://github.com/iom2105))

Maria Prokofieva - ([LinkedIn](https://www.linkedin.com/in/mariapr/)/[Mastodon](https://fosstodon.org/@maria_pro)/[GitHub](https://github.com/maria-pro))

[Emma Rand](https://www.york.ac.uk/biology/our-staff/emma-rand/) - ([LinkedIn](https://www.linkedin.com/in/emma-rand-6b0a61a/)/[Bluesky](https://bsky.app/profile/3mmarand.bsky.social)/[Mastodon](https://fosstodon.org/@3mma@mastodon.social)/[GitHub](https://github.com/3mmaRand))

[Joyce Robbins](http://www.joyce-robbins.com/about/) - ([LinkedIn](https://www.linkedin.com/in/joycerobbins/)/[Twitter](https://twitter.com/jtrnyc)/[GitHub](https://github.com/jtr13))

Dillon Sparks - ([LinkedIn](https://www.linkedin.com/in/dillonsparks1/)/[GitHub](https://github.com/dillonsparks))

[Heather Turner](https://warwick.ac.uk/statistics/staff/academic-research/turner) - ([LinkedIn](https://uk.linkedin.com/in/heathrturnr)/[Bluesky](https://bsky.app/profile/HeathrTurnr.fosstodon.org.ap.brid.gy)/[Mastodon](https://fosstodon.org/@HeathrTurnr)/ [GitHub](https://github.com/hturner))


## Previous Members

We are grateful to everyone who has previously been a member of Forwards:

<!-- end lines with , and one space so easier to maintain alphabetical order, 
but display in paragraph -->

Lorna Maria Aine, 
Tania Allard, 
Yanina Bellini Saibene, 
Jyoti Bhogal, 
Stella Bollman, 
Jenny Bryan, 
Damiano Cerasuolo, 
Pavitra Chakravarty, 
Nic Crane, 
Rudolf Debelak, 
Emily Dodwell, 
Jasmine Dumas, 
Andrea Foulkes, 
John Fox, 
Maya Gans, 
Isabella Gollini, 
Gina Griffin, 
Madlene Hamilton, 
Liz Hare, 
Nujcharee Haswell, 
Claudia Huaylla, 
Zhian N. Kamvar, 
Tatjana Kecojevic, 
Liz Kellogg, 
Os Keyes, 
Joslynn Lee, 
Angela Li, 
Florencia Mangini, 
Imke Mayer, 
Gina Merchant, 
David Meza, 
Ileena Mitra, 
Ritwik Mitra, 
Jesse Mostipak, 
Shakirah Nakalungi, 
Richard Ngamita, 
Wenfeng Qin, 
Augustina Ragwitz, 
Maëlle Salmon, 
Andrea Sánchez-Tapia, 
Dorris Scott, 
Tracy Shen, 
David Smith, 
Carolin Strobl, 
Noa Tamir, 
Samantha Toet, 
Anna Vasylytsya, 
Miljenka Vuko, 
Allison Vuong, 
Charlotte Wickham, 
Hadley Wickham, 
Becca Wilson, 
Yizhe Xu



